module.exports = {
  title: "twi2url",
  description: "twitter 2 url",
  hostname: "ubuntu.local",
  port: 8090,
  pathname: "",
  author: "Takeshi Watanabe",

  feed_item_max: 200,
  retry_max: 2,
  executer: 2,
  url_expander_number: 20,

  long_url_length: 40,
  tweet_max: 200,
  search_max: 100,
  search_type: 'recent',

  fetch_frequency: 1000 * 60 * 20,
  item_generation_frequency: 1000 * 2.5,
  backup_frequency: 1000 * 60,
  timeout: 1000 * 8,
  check_frequency: 1000 * 30,
  retry_failure_max: 1,

  user_agent: [
    'Mozilla/5.0',
    'RSS twi2url ( https://github.com/take-cheeze/rss_twi2url )',
    'by take-cheeze( takechi101010@gmail.com )'
  ].join(),

  selectors: [
    'article', '.article', '.article-body',
    '.POST_BODY', // exblog
    '.articleText', '.subContents', // ameblo
    '.viewbody', // tinami
    '#main', '.main', '.mainmore',
    '#content', '.content', '.caption',
    '.entry-content',
    '.entry_text', '.entry-text',
    '.entry_body', '.entry-body',
    '.ently_text', '.ently-text',
    '.ently_body', '.ently-body',
    '.entry', '.body',
    '#posts', '.Photo',
    'table', 'pre', 'body:first-child',
  ],

  removing_tag: [
    'link', 'script', 'dl', 'object', 'style',
    'frameset', 'frame', 'noframes', 'title', 'form',
    'embed', 'meta',
    '#comment', '.comment_area', '.comment', '#comments-list',
    '.comments', '#comment-form', '#comment_post', '#comment_preview',
    '#comment_form_table',
    '.entryInfoList',
    '.notes', '.note', '#menu',
    '#imageBox',
    '#more-from',
    '#post-tabs', '.post-meta',
    '.related-articles',
    '.pagenav-outer',
    '#sub', '.side',
    '.tweetBtn1201',
    '.appstore',
    '.content_footer'
  ],

  removing_attribute: [
    'pubdate',
    'onclick', 'onmouseover', 'onmouseout', 'illustrations',
    'by', 'cesar', 'onkeypress', 'onsubmit', 'onkeydown',
    'onblur', 'onfocus', 'onkeyup', 'role',
    'columnguid', 'rodrez',
    'preview-capable-text', 'more-text',
    'metrics-loc', 'num-items', 'rating-software',
    'parental-rating', 'adam-id', 'preview-artist',
    'aria-label', 'preview-title', 'columnid',
    'state', 'border_color', 'padding',
    'border_width', 'boder_type', 'onchange'
  ],

  url_expantion_exclude: [
    'twitpic.com/',
    'gist.github.com/',
    'p.twipple.jp/',
    'ideone.com/',
    'instagr.am/p/',
    'lockerz.com/',
  ],

  exclude_filter: [
    'itunes.apple.com/',
    'google.co.jp/search',
    'google.com/search',
    'slash.jp/',
    'blogos.com/',
    'yaraon.blog109.fc2.com/',
    'jin115.com/',
    'togetter.com/',
    'blog.esuteru.com/',
    '/matome.naver.jp/',
    'maps.google.co',
    'favstar.fm/',
    'toranoana.jp/',
    '/www.pixiv.net/member_illust.php',
    'auctions.yahoo.co.jp/',
    'shindanmaker.com/',
    'news',
    'foursquare.com/',
    '4sq.com/',
    '/tou.ch/',
    'amazon.co',
    'youtube.com/',
    'nicovideo.jp/watch/',
    'paper.li/',
    'wikipedia.org',
    'http://homepage1.nifty.com/herumi/diary/',
    '/stream.ogg',
    'gohantabeyo.com/',
    'http://4gamer.net/',
  ],
};
